import { useEffect, useMemo, useState, type ComponentType, type ReactNode } from "#production-react";
import { shouldConvertPastedText, isPastedTextAttachment, createPastedTextFile } from "./composerAttachment";
import { calculateThinkingElapsed, getThinkingTimerAnchor, monotonicNow } from "./thinkingTimer";
import { alpha, Box, ChatIcon, createLucideIcon, createMuiSvgIcon, formatThinkingElapsed, THINKING_TIMER_INTERVAL_MS, Tooltip, Typography, WriteupIcon } from "../../runtime/assistantToolsRuntime.js";

const BookSearchIcon = createLucideIcon("book-search", [["path",{d:"M11 22H5.5a1 1 0 0 1 0-5h4.501",key:"mcbepb"}],["path",{d:"m21 22-1.879-1.878",key:"12q7x1"}],["path",{d:"M3 19.5v-15A2.5 2.5 0 0 1 5.5 2H18a1 1 0 0 1 1 1v8",key:"olfd5n"}],["circle",{cx:"17",cy:"18",r:"3",key:"82mm0e"}]]);
const BookmarkIcon = createLucideIcon("bookmark", [["path",{d:"M17 3a2 2 0 0 1 2 2v15a1 1 0 0 1-1.496.868l-4.512-2.578a2 2 0 0 0-1.984 0l-4.512 2.578A1 1 0 0 1 5 20V5a2 2 0 0 1 2-2z",key:"oz39mx"}]]);
const CalculatorIcon = createLucideIcon("calculator", [["rect",{width:"16",height:"20",x:"4",y:"2",rx:"2",key:"1nb95v"}],["line",{x1:"8",x2:"16",y1:"6",y2:"6",key:"x4nwl0"}],["line",{x1:"16",x2:"16",y1:"14",y2:"18",key:"wjye3r"}],["path",{d:"M16 10h.01",key:"1m94wz"}],["path",{d:"M12 10h.01",key:"1nrarc"}],["path",{d:"M8 10h.01",key:"19clt8"}],["path",{d:"M12 14h.01",key:"1etili"}],["path",{d:"M8 14h.01",key:"6423bh"}],["path",{d:"M12 18h.01",key:"mhygvu"}],["path",{d:"M8 18h.01",key:"lrp35t"}]]);
const ChartLineIcon = createLucideIcon("chart-line", [["path",{d:"M3 3v16a2 2 0 0 0 2 2h16",key:"c24i48"}],["path",{d:"m19 9-5 5-4-4-3 3",key:"2osh9i"}]]);
const QuestionIcon = createLucideIcon("circle-question-mark", [["circle",{cx:"12",cy:"12",r:"10",key:"1mglay"}],["path",{d:"M9.09 9a3 3 0 0 1 5.83 1c0 2-3 3-3 3",key:"1u773s"}],["path",{d:"M12 17h.01",key:"p32p05"}]]);
const CrownIcon = createLucideIcon("crown", [["path",{d:"M11.562 3.266a.5.5 0 0 1 .876 0L15.39 8.87a1 1 0 0 0 1.516.294L21.183 5.5a.5.5 0 0 1 .798.519l-2.834 10.246a1 1 0 0 1-.956.734H5.81a1 1 0 0 1-.957-.734L2.02 6.02a.5.5 0 0 1 .798-.519l4.276 3.664a1 1 0 0 0 1.516-.294z",key:"1vdc57"}],["path",{d:"M5 21h14",key:"11awu3"}]]);
const GitBranchIcon = createLucideIcon("git-branch", [["path",{d:"M15 6a9 9 0 0 0-9 9V3",key:"1cii5b"}],["circle",{cx:"18",cy:"6",r:"3",key:"1h7g24"}],["circle",{cx:"6",cy:"18",r:"3",key:"fqmcym"}]]);
const ListChecksIcon = createLucideIcon("list-checks", [["path",{d:"M13 5h8",key:"a7qcls"}],["path",{d:"M13 12h8",key:"h98zly"}],["path",{d:"M13 19h8",key:"c3s6r1"}],["path",{d:"m3 17 2 2 4-4",key:"1jhpwq"}],["path",{d:"m3 7 2 2 4-4",key:"1obspn"}]]);
const RefreshIcon = createLucideIcon("refresh-ccw", [["path",{d:"M21 12a9 9 0 0 0-9-9 9.75 9.75 0 0 0-6.74 2.74L3 8",key:"14sxne"}],["path",{d:"M3 3v5h5",key:"1xhq8a"}],["path",{d:"M3 12a9 9 0 0 0 9 9 9.75 9.75 0 0 0 6.74-2.74L21 16",key:"1hlbsb"}],["path",{d:"M16 16h5v5",key:"ccwih5"}]]);
const RotateIcon = createLucideIcon("rotate-ccw", [["path",{d:"M3 12a9 9 0 1 0 9-9 9.75 9.75 0 0 0-6.74 2.74L3 8",key:"1357e3"}],["path",{d:"M3 3v5h5",key:"1xhq8a"}]]);
const ScaleIcon = createLucideIcon("scale", [["path",{d:"M12 3v18",key:"108xh3"}],["path",{d:"m19 8 3 8a5 5 0 0 1-6 0zV7",key:"zcdpyk"}],["path",{d:"M3 7h1a17 17 0 0 0 8-2 17 17 0 0 0 8 2h1",key:"1yorad"}],["path",{d:"m5 8 3 8a5 5 0 0 1-6 0zV7",key:"eua70x"}],["path",{d:"M7 21h10",key:"1b0cd5"}]]);
const ThumbsUpIcon = createLucideIcon("thumbs-up", [["path",{d:"M15 5.88 14 10h5.83a2 2 0 0 1 1.92 2.56l-2.33 8A2 2 0 0 1 17.5 22H4a2 2 0 0 1-2-2v-8a2 2 0 0 1 2-2h2.76a2 2 0 0 0 1.79-1.11L12 2a3.13 3.13 0 0 1 3 3.88Z",key:"emmmcr"}],["path",{d:"M7 10v12",key:"1qc93n"}]]);
const CollapseIcon = createMuiSvgIcon(<path d="m14 4 2.29 2.29-2.88 2.88 1.42 1.42 2.88-2.88L20 10V4zm-4 0H4v6l2.29-2.29 4.71 4.7V20h2v-8.41l-5.29-5.3z"/>);

export const THREAD_TOUR_TARGETS = { mainPanel:"thread-main-panel", mainPanelPopoverAnchor:"thread-main-panel-popover-anchor", viewport:"thread-viewport", composer:"thread-composer", composerInput:"thread-composer-input", composerControls:"thread-composer-controls", composerOperation:"thread-composer-operation", composerOperationChat:"thread-composer-operation-chat", composerOperationReferee:"thread-composer-operation-referee", composerOperationQuestion:"thread-composer-operation-question", composerOperationCompute:"thread-composer-operation-compute", composerOperationVisualization:"thread-composer-operation-visualization", composerOperationWriteup:"thread-composer-operation-writeup", composerOperationLiteratureSearch:"thread-composer-operation-literature-search", composerOperationNextSteps:"thread-composer-operation-next-steps", composerNextSteps:"thread-composer-next-steps", composerProRun:"thread-composer-pro-run", composerModel:"thread-composer-model", composerAttachFiles:"thread-composer-attach-files", composerLatex:"thread-composer-latex", composerSubmit:"thread-composer-submit", queryNavigator:"thread-query-navigator", tourButton:"thread-tour-button", contextUsage:"thread-context-usage", variableHighlights:"thread-variable-highlights", chatSidebar:"thread-chat-sidebar", chatSidebarToolbar:"thread-chat-sidebar-toolbar", chatSidebarNewChat:"thread-chat-sidebar-new-chat", chatSidebarCreateFolder:"thread-chat-sidebar-create-folder", chatSidebarSearch:"thread-chat-sidebar-search", chatSidebarClose:"thread-chat-sidebar-close", chatSidebarContent:"thread-chat-sidebar-content", chatSidebarExplorer:"thread-chat-sidebar-explorer", chatSidebarFooter:"thread-chat-sidebar-footer", workspacePanelToggle:"thread-workspace-panel-toggle", workspaceThemeMode:"thread-workspace-theme-mode", workspaceMoreActions:"thread-workspace-more-actions", branchResponse:"thread-branch-response", structuredResponseTabs:"thread-structured-response-tabs", writeupTab:"thread-writeup-tab", writeupActions:"thread-writeup-actions", writeupLatexEditor:"thread-writeup-latex-editor", writeupPdf:"thread-writeup-pdf" } as const;
export const OPERATION_TOUR_TARGETS = { chat: THREAD_TOUR_TARGETS.composerOperationChat, question: THREAD_TOUR_TARGETS.composerOperationQuestion, "lit-search": THREAD_TOUR_TARGETS.composerOperationLiteratureSearch, compute: THREAD_TOUR_TARGETS.composerOperationCompute, visualization: THREAD_TOUR_TARGETS.composerOperationVisualization, writeup: THREAD_TOUR_TARGETS.composerOperationWriteup, referee: THREAD_TOUR_TARGETS.composerOperationReferee, "next-steps": THREAD_TOUR_TARGETS.composerOperationNextSteps } as const;
export const tourTargetSelector = (target: string) => `[data-thread-tour-target="${target}"]`;
const operationIcons: Record<string, ComponentType<any>> = { chat: ChatIcon, question: QuestionIcon, compute: CalculatorIcon, referee: ScaleIcon, visualization: ChartLineIcon, writeup: WriteupIcon, "lit-search": BookSearchIcon, "next-steps": ListChecksIcon };
export function OperationIcon({ operation, className, size = 16, strokeWidth = 2.2, tooltip }: { operation?: string | null; className?: string; size?: number; strokeWidth?: number; tooltip?: boolean }) { const Icon = operation ? operationIcons[operation] : undefined; if (!operation || !Icon) return null; const icon = <Icon aria-hidden="true" className={className} focusable="false" size={size} strokeWidth={strokeWidth}/>; return tooltip ? <Tooltip title={`${operation} operation`} arrow={true} placement="top">{icon}</Tooltip> : icon; }
export const OPERATION_OPTIONS = [{value:"chat",label:"Auto",description:"Automatically chooses the best operation for your prompt."},{value:"question",label:"Question",description:"Gives a structured answer to a math or STEM question."},{value:"lit-search",label:"Literature Search",description:"Finds and organizes relevant research and sources."},{value:"compute",label:"Compute",description:"Request a python calculation in natural language."},{value:"visualization",label:"Visualization",description:"Creates an appropriate plot, graph, diagram, or visual artifact."},{value:"writeup",label:"Writeup",description:"Produces a polished, self-contained LaTeX note."},{value:"referee",label:"Referee",description:"Stress-tests a proof or derivation for gaps and errors."},{value:"next-steps",label:"Next Steps",description:"Suggests selectable ways to continue the current work."}] as const;
export const EXPLICIT_OPERATION_OPTIONS = OPERATION_OPTIONS.filter((option) => option.value !== "chat");
const operationRunPrompts: Record<string,string> = { referee:"Run referee review on this chat.", question:"Answer the latest question in this chat.", compute:"Run a concrete computation for this chat.", visualization:"Create a visualization for this chat.", writeup:"Create a writeup from this chat.", "lit-search":"Run literature search for this chat.", "next-steps":"Generate next-step choices for this chat." };
export const getOperationRunPrompt = (operation: string) => operationRunPrompts[operation];

interface FrameTheme { spacing(value: number): string; shape: { borderRadiusPx: number }; palette: { primary: { main: string } }; breakpoints: { down(value: number): string } }
const frameStyles = (theme: FrameTheme) => ({display:"flex",width:"min(calc(100% - 3.55rem), 76rem)",gap:theme.spacing(1.8),marginInline:"auto",transform:"translateX(-1.775rem)",paddingBlock:theme.spacing(1.3),[theme.breakpoints.down(720)]:{gap:theme.spacing(1.4),width:"min(calc(100% - 0.5rem), 76rem)",transform:"translateX(-0.5rem)"}}); const iconColumnStyles=(theme:FrameTheme)=>({flex:"0 0 auto",width:"2.65rem",display:"flex",flexDirection:"column",alignItems:"center",gap:theme.spacing(0.55),[theme.breakpoints.down(720)]:{width:"2.3rem"}}); const avatarStyles=(theme:FrameTheme)=>({width:"2.65rem",height:"2.65rem",borderRadius:theme.shape.borderRadiusPx,display:"inline-flex",alignItems:"center",justifyContent:"center",overflow:"hidden",backgroundColor:alpha(theme.palette.primary.main,0.1),color:theme.palette.primary.main,boxShadow:`inset 0 0 0 1px ${alpha(theme.palette.primary.main,0.08)}`,[theme.breakpoints.down(720)]:{width:"2.3rem",height:"2.3rem"}});
export function AssistantMessageFrame({ children }: { children: ReactNode }) { return <Box sx={frameStyles}><Box sx={iconColumnStyles}><Box sx={avatarStyles}/></Box><Box sx={{minWidth:0,flex:1}}>{children}</Box></Box>; }
export function ThinkingElapsedLabel({ runId, startedAt, className, color, titlePrefix="Thinking for", variant="body1" }: { runId:string; startedAt:number; className?:string; color?:string; titlePrefix?:string; variant?:string }) { const anchor=useMemo(()=>getThinkingTimerAnchor(runId,startedAt),[runId,startedAt]); const [now,setNow]=useState(()=>monotonicNow()); useEffect(()=>{setNow(monotonicNow()); const interval=window.setInterval(()=>setNow(monotonicNow()),THINKING_TIMER_INTERVAL_MS); return()=>window.clearInterval(interval);},[anchor.runId]); const label=formatThinkingElapsed(calculateThinkingElapsed(anchor,now)); return <Typography component="span" className={className} color={color} variant={variant} title={`${titlePrefix} ${label}`}>{label}</Typography>; }

export { BookmarkIcon, CrownIcon, GitBranchIcon, RotateIcon, RefreshIcon, ThumbsUpIcon, CalculatorIcon, QuestionIcon, CollapseIcon, shouldConvertPastedText, isPastedTextAttachment, createPastedTextFile };
