export interface PendingAgentTask { taskId: string; revision: number; status: string; objective: string; [key: string]: unknown }
export interface PendingAgentOperation { id: string; revision: number; status: string; operation: string; taskId: string | null; [key: string]: unknown }
export interface PendingAgentOutput { id: string; status: string; operation: string; taskId: string | null; [key: string]: unknown }
export interface PendingAgentSnapshot { runId: string | null; tasks: PendingAgentTask[]; operations: PendingAgentOperation[]; outputs: PendingAgentOutput[] }

export function parseAgentTaskIndex(taskId: string): number { const match = /^agent-task-(0|[1-9]\d*)$/.exec(taskId); const index = match ? Number(match[1]) : Number.NaN; if (!Number.isSafeInteger(index)) throw new Error(`Agent task id is malformed: ${taskId}.`); return index; }
export function sortAgentTasks(tasks: readonly PendingAgentTask[]): PendingAgentTask[] { return [...tasks].sort((left, right) => parseAgentTaskIndex(left.taskId) - parseAgentTaskIndex(right.taskId)); }
export function applyAgentTask(snapshot: PendingAgentSnapshot, runId: string, task: PendingAgentTask): PendingAgentSnapshot { parseAgentTaskIndex(task.taskId); const tasks = snapshot.runId === runId ? snapshot.tasks : []; const operations = snapshot.runId === runId ? snapshot.operations : []; const outputs = snapshot.runId === runId ? snapshot.outputs : []; const index = tasks.findIndex((item) => item.taskId === task.taskId); const existing = tasks[index]; if (existing && existing.revision >= task.revision) return snapshot; return { runId, tasks: sortAgentTasks(index === -1 ? [...tasks, task] : tasks.map((item, itemIndex) => itemIndex === index ? task : item)), operations, outputs }; }
export function createAgentResetSnapshot(runId: string, tasks: PendingAgentTask[], operations: PendingAgentOperation[], outputs: PendingAgentOutput[]): PendingAgentSnapshot { if (new Set(tasks.map((task) => task.taskId)).size !== tasks.length) throw new Error("Agent task reset snapshot contains duplicate task ids."); if (new Set(operations.map((operation) => operation.id)).size !== operations.length) throw new Error("Agent task reset snapshot contains duplicate operation ids."); if (new Set(outputs.map((output) => output.id)).size !== outputs.length) throw new Error("Agent task reset snapshot contains duplicate operation output ids."); const operationsById = new Map(operations.map((operation) => [operation.id, operation])); for (const output of outputs) { const operation = operationsById.get(output.id); if (!operation || operation.status !== output.status || operation.operation !== output.operation || operation.taskId !== output.taskId) throw new Error("Agent task reset snapshot output does not match its operation."); } return { runId, tasks: sortAgentTasks(tasks), operations, outputs }; }
export interface PendingTaskRevision { sequence: number; revision: number }
export function mergeAgentResetSnapshot(current: PendingAgentSnapshot, reset: PendingAgentSnapshot, resetSequence: number, revisions: Map<string, PendingTaskRevision>): PendingAgentSnapshot { if (current.runId !== reset.runId) return reset; if (!reset.runId) throw new Error("Agent reset snapshot is missing its run id."); const currentTasks = new Map(current.tasks.map((task) => [task.taskId, task])); const resetIds = new Set(reset.tasks.map((task) => task.taskId)); const tasks = reset.tasks.map((task) => { const revision = revisions.get(task.taskId); const currentTask = currentTasks.get(task.taskId); return revision && revision.sequence > resetSequence && revision.revision > task.revision && currentTask && currentTask.revision >= revision.revision ? currentTask : task; }); for (const task of current.tasks) if (!resetIds.has(task.taskId)) tasks.push(task); const remainingResetOperations = new Map(reset.operations.map((operation) => [operation.id, operation])); const operations = current.operations.map((operation) => { const resetOperation = remainingResetOperations.get(operation.id); if (!resetOperation) return operation; remainingResetOperations.delete(operation.id); return resetOperation.revision >= operation.revision ? resetOperation : operation; }); operations.push(...remainingResetOperations.values()); const outputs = new Map(current.outputs.map((output) => [output.id, output])); for (const output of reset.outputs) outputs.set(output.id, output); return createAgentResetSnapshot(reset.runId, tasks, operations, [...outputs.values()]); }

const operationLabels: Record<string,string> = { chat:"Auto",question:"Question","lit-search":"Literature Search",compute:"Compute",visualization:"Visualization",writeup:"Writeup",referee:"Referee","next-steps":"Next Steps" };
export function getPendingStatusLabel(activeRun: { workflowMode?: string; status?: string } | null | undefined, phase: string, tasks: PendingAgentTask[] = [], operations: PendingAgentOperation[] = []): string { if (activeRun?.workflowMode === "agent") { if (phase === "generating") return "Preparing the answer..."; const runningTasks=tasks.filter((task)=>task.status==="running"); if(runningTasks.length===1)return `Working on ${runningTasks[0].objective}...`; if(runningTasks.length>1)return `Working on ${runningTasks.length} tasks...`; const plannedTasks=tasks.filter((task)=>task.status==="planned"); if(plannedTasks.length===1)return `Preparing ${plannedTasks[0].objective}...`; if(plannedTasks.length>1)return `Preparing ${plannedTasks.length} tasks...`; const runningOperations=operations.filter((operation)=>operation.status==="running"); const plannedOperations=operations.filter((operation)=>operation.status==="planned"); const current=runningOperations.length>0?runningOperations:plannedOperations; const verb=runningOperations.length>0?"Running":"Preparing"; if(current.length===1){const label=operationLabels[current[0].operation];if(!label)throw new Error(`Missing label for Agent operation "${current[0].operation}".`);return `${verb} ${label}...`;} if(current.length>1)return `${verb} ${current.length} operations...`; return tasks.length>0||operations.length>0?"Preparing the answer...":"Planning tasks..."; } if(activeRun?.status==="queued")return "Queued..."; if(phase==="reasoning")return "Reasoning ..."; if(phase==="generating")return "Generating Response"; return "Waiting for model output..."; }
