const MAX_TIMER_ANCHORS = 250;
const FUTURE_CLOCK_WARNING_MS = 2000;
export interface ThinkingTimerAnchor { runId: string; observedMonotonicTime: number; initialElapsedMs: number }
const anchors = new Map<string, ThinkingTimerAnchor>(); const warnedRunIds = new Set<string>();
export function monotonicNow(): number { return typeof performance === "undefined" ? Date.now() : performance.now(); }
function trimAnchors(protectedRunId: string): void { while (anchors.size > MAX_TIMER_ANCHORS) { const first = anchors.keys().next().value as string | undefined; if (!first) return; if (first === protectedRunId) { const anchor = anchors.get(first); if (!anchor) return; anchors.delete(first); anchors.set(first, anchor); continue; } anchors.delete(first); warnedRunIds.delete(first); } }
export function createThinkingTimerAnchor(runId: string, startedAt: number, wallNow = Date.now(), observedNow = monotonicNow()): ThinkingTimerAnchor { if (!Number.isFinite(startedAt)) throw new Error("Thinking elapsed timer requires a finite start time."); const future = startedAt - wallNow; if (future > FUTURE_CLOCK_WARNING_MS && !warnedRunIds.has(runId)) { warnedRunIds.add(runId); console.warn("Chat run start time is ahead of the device clock; using a local elapsed timer anchor.", { runId, futureStartedAtMs: Math.round(future), serverStartedAt: new Date(startedAt).toISOString(), clientObservedAt: new Date(wallNow).toISOString() }); } return { runId, observedMonotonicTime: observedNow, initialElapsedMs: Math.max(0, wallNow - startedAt) }; }
export function getThinkingTimerAnchor(runId: string, startedAt: number): ThinkingTimerAnchor { const existing = anchors.get(runId); if (existing) { anchors.delete(runId); anchors.set(runId, existing); return existing; } const anchor = createThinkingTimerAnchor(runId, startedAt); anchors.set(runId, anchor); trimAnchors(runId); return anchor; }
export function calculateThinkingElapsed(anchor: ThinkingTimerAnchor, currentMonotonicTime: number): number { return anchor.initialElapsedMs + Math.max(0, currentMonotonicTime - anchor.observedMonotonicTime); }
