import { B as Box, g as alpha, S as Stack, T as Typography, e as Paper } from "../chunks/index-BM3ZINIl.jsx";
import { C as CopyButton } from "../chunks/CopyButton-BcOsqrNJ.js";
import { i as isVariableDefinitions, c as CitationLink, h as isLiteratureSources, f as stringifySectionValue, j as getStructuredSections, s as getSectionCopyContent } from "../chunks/assistantStructuredResponseLazy-CCAemx3W.jsx";
import { i as isNextStepChoices, N as NextStepChoices, a as NextStepsResponse } from "../chunks/NextStepsResponse-NcFjw3w7.jsx";
import { r as transformMarkdownMath, T as Tabs, a as Tab } from "../chunks/MarkdownHighlights-C-ZhT8z1.jsx";
import { S as StructuredMarkdown } from "../chunks/StructuredMarkdown-DAWLLRpf.js";
import { e as Accordion, f as AccordionSummary, E as ExpandMoreIcon, h as AccordionDetails } from "../chunks/MessageBubble-DqxHrk03.jsx";
import { M as Chip } from "../chunks/MChip-DiH8NXBU.jsx";
import { C as Card } from "../chunks/Card-Bf0WPnf4.jsx";
import { lazy } from "react";
const VisualizationStructuredSection=lazy(()=>import("../chunks/VisualizationStructuredSection-BK_R26-B.js").then(module=>({default:module.VisualizationStructuredSection})));
const ComputeStructuredSection=lazy(()=>import("../chunks/ComputeStructuredSection-C40NdNj6.js").then(module=>({default:module.ComputeStructuredSection})));
const WriteupStructuredResponsePanel=lazy(()=>import("../chunks/WriteupStructuredResponsePanel-CPg9TOt6.js").then(module=>({default:module.WriteupStructuredResponsePanel})));
export { Accordion, AccordionDetails, AccordionSummary, alpha, Box, Card, Chip, CitationLink, ComputeStructuredSection, CopyButton, ExpandMoreIcon, getSectionCopyContent, getStructuredSections, isLiteratureSources, isNextStepChoices, isVariableDefinitions, NextStepChoices, NextStepsResponse, Paper, Stack, stringifySectionValue, StructuredMarkdown, Tab, Tabs, transformMarkdownMath, Typography, VisualizationStructuredSection, WriteupStructuredResponsePanel };
