import { lazy } from "react";
import { g as alpha, B as Box, C as CircularProgress, t as toast, V as IconButton, X as CloseIcon, _ as Button, T as Typography } from "../chunks/index-BM3ZINIl.jsx";
import { A as Alert } from "../chunks/Alert-DnFVD8li.jsx";
import { b as extractLatexPreview } from "../chunks/latexPreview-B9IEPCtV.js";
import { a as Markdown } from "../chunks/Markdown-Dh8LhaRc.jsx";
import { T as Tabs, a as Tab } from "../chunks/MarkdownHighlights-C-ZhT8z1.jsx";
import { u as useCreateLatexDocument, c as useSourceCompile, e as useCompileJob, i as isCompileJobPending, j as MAIN_LATEX_FILE_NAME } from "../chunks/useLatexQueries-DBpKOPUv.js";
import { u as usePdfObjectUrl } from "../chunks/usePdfObjectUrl-Cd7ol8-S.js";
import { a as useAttachmentContent } from "../chunks/useAttachmentContent-15uaQfvd.js";
import { u as useControlOrMetaShortcut } from "../chunks/useControlOrMetaShortcut-DL7j4WBM.js";
import { D as Drawer } from "../chunks/Drawer-ByPJ5WV0.jsx";
import { T as TextField } from "../chunks/TextField-D8vc_sXz.jsx";
import { P as PlayIcon } from "../chunks/play-3zl_nde-.js";
import { F as PlusFileIcon } from "../chunks/file-plus-_oOf3yl8.js";
const LatexSourceEditor=lazy(()=>import("../chunks/source-editor-CGMzw50e.jsx").then(module=>({default:module.p.LatexSourceEditor})));
export { Alert, alpha, Box, Button, CircularProgress, CloseIcon, Drawer, extractLatexPreview, IconButton, LatexSourceEditor, MAIN_LATEX_FILE_NAME, Markdown, PlayIcon, PlusFileIcon, Tab, Tabs, TextField, toast, Typography, useAttachmentContent, useCompileJob, useControlOrMetaShortcut, useCreateLatexDocument, usePdfObjectUrl, useSourceCompile, isCompileJobPending };
