import { ax as apiClient, aj as apiBase, g as alpha, B as Box, _ as Button, T as Typography, C as CircularProgress, S as Stack, p as useQueryClient, b1 as getRunErrorMessage, b2 as shouldRefreshProject, t as toast, ai as getErrorMessage, s as queryKeys, V as TooltipIconButton } from "../chunks/index-BM3ZINIl.jsx";
import { createLucideIcon } from "lucide-react";
import { u as useQuery } from "../chunks/useQuery-DM2qiUYb.js";
import { u as useMutation } from "../chunks/useMutation-C1SgG9wr.js";
import { t as mapChat, u as updateChat } from "../chunks/chatsApi-Ck-JYICO.js";
import { r as rollbackChat, n as notifyChatChanged } from "../chunks/chatQueryCache-DOdNJrP_.js";
import { u as useChatPolling, f as useExecutionModes, h as useChat } from "../chunks/threadMessageListLazy-ghC-RLRq.js";
import { u as useComposerAttachments, b as useChatSubmission, A as ACCEPTED_ATTACHMENT_TYPES, c as ChatSubmissionProvider } from "../chunks/ChatPanelMoreMenu-B1X9SOWN.jsx";
import { a as cacheKeys } from "../chunks/cache-BNzcfneg.js";
import { u as useConfirmation } from "../chunks/OpenInNewRounded-D-7V5TzF.jsx";
import { M as MessageAttachments } from "../chunks/MessageAttachments-nUg1LIry.js";
import { C as ComposerAttachmentCard } from "../chunks/ComposerAttachmentCard-BVMHeN2h.js";
import { M as MessageBubble, d as MessageSources } from "../chunks/MessageBubble-DqxHrk03.jsx";
import { f as useLatexEditProposal } from "../chunks/useLatexQueries-DBpKOPUv.js";
import { L as ACTIVE_PROJECT_CHAT_MESSAGE } from "../chunks/latexProjectChatMessages-Cty9Jluh.js";
import { M as Chip } from "../chunks/MChip-DiH8NXBU.jsx";
import { a as Markdown } from "../chunks/Markdown-Dh8LhaRc.jsx";
import { A as Alert } from "../chunks/Alert-DnFVD8li.jsx";
import { T as TextField } from "../chunks/TextField-D8vc_sXz.jsx";
import { E as EraserIcon } from "../chunks/eraser-B4pclN2p.js";
import { P as PanelCloseIcon } from "../chunks/panel-right-close-BXzsVzHe.js";
const getProjectChat=(documentId)=>apiClient.post(apiBase,`latex/documents/${encodeURIComponent(documentId)}/chat`,{}).then(mapChat);
export { ACCEPTED_ATTACHMENT_TYPES, ACTIVE_PROJECT_CHAT_MESSAGE, Alert, alpha, Box, Button, cacheKeys, ChatSubmissionProvider, Chip, CircularProgress, ComposerAttachmentCard, createLucideIcon, EraserIcon, getErrorMessage, getProjectChat, getRunErrorMessage, Markdown, MessageAttachments, MessageBubble, MessageSources, notifyChatChanged, PanelCloseIcon, queryKeys, rollbackChat, shouldRefreshProject, Stack, TextField, toast, TooltipIconButton, Typography, updateChat, useChat, useChatPolling, useChatSubmission, useComposerAttachments, useConfirmation, useExecutionModes, useLatexEditProposal, useMutation, useQuery, useQueryClient };
