import type { ComponentType } from "react";
export const ArrowBackIcon: ComponentType<any>;
export const AssistantMessage: ComponentType<any>;
export const AutoAwesomeRounded: ComponentType<any>;
export const Avatar: ComponentType<any>;
export const Box: ComponentType<any>;
export const EmptyState: ComponentType<any>;
export const LinkButton: ComponentType<any>;
export const LinkOffIcon: ComponentType<any>;
export const LoadingState: ComponentType<any>;
export const MarkdownScope: ComponentType<any>;
export const SharedIcon: ComponentType<any>;
export const Stack: ComponentType<any>;
export const Typography: ComponentType<any>;
export const UserMessage: ComponentType<any>;
export function alpha(color: string, opacity: number): string;
export const UNTITLED_CHAT_TITLE: string;
export const chatQueryKeys: { sharedChat(id: string): unknown[] };
export const sharedChatRoute: { useParams(): { chatId: string } };
export function getErrorMessage(error: unknown): string;
export function getMessageMathMacros(messages: unknown[]): Array<Record<string, string>>;
export function useQuery<T>(options: Record<string, unknown>): { data?: T; error?: unknown; isPending: boolean; isError: boolean };
