import { r as d, j as s, S as _Component4, T as _Component2 } from "./index-BM3ZINIl.js";
import { A as _Component, c as A, d as I } from "./SupportingArtifactCard-B1XjYGZI.js";
import { a as _Component3 } from "./Markdown-Dh8LhaRc.js";
import { G as S } from "./GeneratedArtifactContent-DZ9NE8JY.js";
import { M as _Component5 } from "./MChip-DiH8NXBU.js";
import "./assistantStructuredResponseLazy-CCAemx3W.js";
import "./useQuery-DM2qiUYb.js";
import "./triangle-alert-C5eP7BuB.js";
import "./circle-check-B9fquZbm.js";
import "./Divider-BcuihGce.js";
import "./LoadingSection-wWBu2CqJ.js";
import "./ThinkingElapsedLabel-DKCKD95O.js";
import "./MarkdownHighlights-C-ZhT8z1.js";
import "./TextField-D8vc_sXz.js";
import "./index-Yb6ONXKu.js";
import "./streamNdjson-sRiOwtSP.js";
import "./MessageBubble-DqxHrk03.js";
import "./OpenInNewRounded-D-7V5TzF.js";
import "./FormControlLabel-CQvCddOM.js";
import "./CopyButton-BcOsqrNJ.js";
import "./katex.min-ADdKj7O-.js";
import "./file-code-corner-DV79SyC0.js";
import "./code-xml-DmfSENe3.js";
import "./Drawer-ByPJ5WV0.js";
import "./useAttachmentContent-15uaQfvd.js";
import "./attachmentsApi-BHgxfYft.js";
import "./authFetch-DXjDztUP.js";
import "./Card-Bf0WPnf4.js";
import "./index-DzMT-bSF.js";
import "./ViewportVisualizationFigure-BIlJdDlH.js";
import "./useLatexQueries-DBpKOPUv.js";
import "./search-CE89ACSU.js";
import "./useMutation-C1SgG9wr.js";
import "./useInfiniteQuery-CdNTitqC.js";
import "./cache-BNzcfneg.js";
import "./downloadBlob-CusuPFei.js";
import "./Alert-DnFVD8li.js";
import "./ListItemIcon-CaLBil7Q.js";
import "./file-input-BGVdGffy.js";
import "./panel-right-close-BXzsVzHe.js";
import "./chevron-left-BwEFN4zp.js";
import "./minimize-2-DiBwEVni.js";
import "./maximize-2-B07z4fzS.js";
import "./zoom-in-uCZ29dqq.js";
import "./square-D0gg5_xj.js";
import "./eraser-B4pclN2p.js";
import "./DebouncedTextField-DEJkKI5N.js";
import "./Slider-v2yN6a4G.js";
import "./play-3zl_nde-.js";
import "./pencil-DHia85Iy.js";
import "./circle-DSozMRKK.js";
const x = e => ({
  "& :where(.markdown-code-block)": {
    marginTop: 0,
    borderRadius: e.shape.radiusSmPx
  }
});
const _Component6 = d.memo(function ({
  calculation: t,
  artifacts: o,
  mathSyntax: n
}) {
  const r = t.output;
  const a = [r == null ? undefined : r.response, r == null ? undefined : r.stderr, r != null && r.stdoutTruncated ? "stdout was truncated." : null, r != null && r.stderrTruncated ? "stderr was truncated." : null].filter(i => i != null && !!i.trim()).join(`

`);
  return <_Component4 spacing={0.95}><_Component languageLabel={t.runtime === "sage" ? "Sage" : "Python"} source={t.code} />{(r == null ? undefined : r.stdout.trim()) && <s.Fragment><_Component2 variant="subtitle2">Output</_Component2><_Component3 content={`\`\`\`text
${r.stdout.trim()}
\`\`\``} mathSyntax={n} sx={x} /></s.Fragment>}{a && <s.Fragment><_Component2 variant="subtitle2" color="error">Diagnostics</_Component2><_Component3 content={`\`\`\`text
${a}
\`\`\``} mathSyntax={n} sx={x} /></s.Fragment>}{t.inputAttachmentIds.length > 0 && <_Component2 variant="body2" color="text.secondary">Inputs: {t.inputAttachmentIds.join(", ")}</_Component2>}{o.length > 0 && <S artifactRefs={o.map(i => ({
      artifact_name: i.name,
      caption: `Supporting calculation artifact: ${i.name}.`,
      alt_text: `Artifact generated by the ${t.runtime === "sage" ? "Sage" : "Python"} calculation: ${i.name}.`,
      python_code: t.code
    }))} artifacts={o} mathSyntax={n}><_Component2 variant="subtitle2">Generated artifacts</_Component2></S>}{o.length === 0 && r && r.artifacts.length > 0 && <_Component4 spacing={0.5}><_Component2 variant="subtitle2">Generated files</_Component2>{r.artifacts.map(i => <_Component2 variant="body2" color="text.secondary" key={`${t.callId}:${i.name}`}>{i.name} · {i.mimeType} · {i.sizeBytes} bytes</_Component2>)}</_Component4>}</_Component4>;
});
const f = e => e !== null && typeof e == "object" && !Array.isArray(e) ? e : null;
const T = e => e === "run_computation" || e === "run_python";
const h = e => {
  if (e.toolName === "run_python") {
    return "python";
  }
  if (e.toolName !== "run_computation") {
    return null;
  }
  const t = f(e.arguments.output);
  const o = e.arguments.runtime ?? (t == null ? undefined : t.runtime);
  if (o === "python" || o === "sage") {
    return o;
  } else {
    return null;
  }
};
const $ = e => Array.isArray(e) ? e.flatMap(t => {
  const o = f(t);
  if (!o || typeof o.name != "string" || typeof o.mime_type != "string" || typeof o.size_bytes != "number") {
    return [];
  } else {
    return [{
      attachmentId: typeof o.attachment_id == "string" ? o.attachment_id : null,
      name: o.name,
      mimeType: o.mime_type,
      sizeBytes: o.size_bytes
    }];
  }
}) : [];
const C = e => {
  const t = f(e);
  if (!t || typeof t.success != "boolean") {
    return null;
  } else {
    return {
      success: t.success,
      executed: typeof t.executed == "boolean" ? t.executed : true,
      stdout: typeof t.stdout == "string" ? t.stdout : "",
      stdoutTruncated: t.stdout_truncated === true,
      stderr: typeof t.stderr == "string" ? t.stderr : "",
      stderrTruncated: t.stderr_truncated === true,
      exitCode: typeof t.exit_code == "number" ? t.exit_code : null,
      timedOut: t.timed_out === true,
      durationMs: typeof t.duration_ms == "number" ? t.duration_ms : 0,
      response: typeof t.response == "string" ? t.response : null,
      errorType: typeof t.error_type == "string" ? t.error_type : null,
      artifacts: $(t.artifacts)
    };
  }
};
const k = e => {
  const t = (e.toolCalls ?? []).filter(n => n.toolType === "function_call" && !!n.callId && h(n));
  const o = new Map();
  for (const n of e.toolCalls ?? []) {
    if (n.toolType !== "function_call_output" || !n.callId || !T(n.toolName)) {
      continue;
    }
    const r = C(n.arguments.output);
    if (r) {
      o.set(`${n.toolName}:${n.callId}`, r);
    }
  }
  return t.flatMap(n => {
    const r = h(n);
    const a = n.arguments.code;
    if (!r || typeof a != "string" || !n.callId) {
      return [];
    }
    const i = Array.isArray(n.arguments.input_attachment_ids) ? n.arguments.input_attachment_ids.filter(p => typeof p == "string") : [];
    return [{
      callId: n.callId,
      runtime: r,
      code: a,
      inputAttachmentIds: i,
      output: o.get(`${n.toolName}:${n.callId}`) ?? null
    }];
  });
};
const N = e => e < 1000 ? `${Math.round(e)} ms` : `${(e / 1000).toFixed(e < 10000 ? 2 : 1)} s`;
const z = {
  flexWrap: "wrap",
  alignItems: "center",
  width: "100%"
};
const F = {
  marginLeft: "auto",
  display: "flex",
  alignItems: "center",
  gap: 0.5,
  flexShrink: 0
};
const M = {
  completed: {
    label: "Completed",
    color: "success"
  },
  partial: {
    label: "Partial",
    color: "warning"
  },
  failed: {
    label: "Failed",
    color: "error"
  }
};
const P = d.memo(function ({
  toolCalls: t,
  artifacts: o,
  status: n,
  mathSyntax: r
}) {
  const a = d.useMemo(() => k({
    toolCalls: t
  }), [t]);
  const i = [...new Set(a.map(m => m.runtime))];
  const p = typeof n == "string" ? M[n] : undefined;
  const g = [...new Set(a.map(m => m.code))].join(`

`);
  const _ = a.length === 1 ? `calculation-${a[0].callId.slice(0, 8)}.py` : "calculations.py";
  if (a.length === 0) {
    return null;
  } else {
    return <_Component4 spacing={0.5}><_Component4 direction="row" spacing={0.75} useFlexGap={true} sx={z}>{p && <_Component5 size="small" color={p.color} label={p.label} />}{i.map(m => <_Component5 size="small" variant="outlined" label={m === "sage" ? "Sage" : "Python"} key={m} />)}{a.map(m => m.output && <_Component5 size="small" variant="outlined" label={N(m.output.durationMs)} key={`${m.callId}:duration`} />)}{g && <_Component4 direction="row" sx={F}><A fileName={_} source={g} /></_Component4>}</_Component4>{a.map(m => <_Component6 calculation={m} artifacts={o.filter(j => j.originatingCallId === m.callId)} mathSyntax={r} key={m.callId} />)}</_Component4>;
  }
});
const Ft = ({
  artifacts: e,
  artifactMessage: t,
  mathSyntax: o,
  status: n,
  toolCalls: r
}) => {
  const a = d.useMemo(() => t ? I(t, "compute") : [], [t]);
  return <P toolCalls={r} artifacts={e ?? a} status={n} mathSyntax={o} />;
};
export { Ft as ComputeStructuredSection };
