import { Fragment, memo, useMemo } from "#production-react";

import type { Artifact } from "../../runtime/artifactUiRuntime.js";
import {
  Chip,
  CodeSourceCard,
  DownloadSourceButton,
  getArtifactsFromMessage,
  InlineMarkdown,
  Stack,
  Typography,
} from "../../runtime/computeSectionRuntime.js";
import { GeneratedArtifactContent } from "../artifacts/GeneratedArtifactContent";
import {
  collectCalculations,
  formatComputationDuration,
  type Calculation,
  type ComputeToolCall,
} from "./computeToolCalls";

const codeBlockStyles = (theme: { shape: { radiusSmPx: number } }) => ({
  "& :where(.markdown-code-block)": { marginTop: 0, borderRadius: theme.shape.radiusSmPx },
});

const CalculationDetails = memo(function CalculationDetails({
  calculation,
  artifacts,
  mathSyntax,
}: {
  calculation: Calculation;
  artifacts: Artifact[];
  mathSyntax?: string;
}) {
  const output = calculation.output;
  const diagnostics = [
    output?.response,
    output?.stderr,
    output?.stdoutTruncated ? "stdout was truncated." : null,
    output?.stderrTruncated ? "stderr was truncated." : null,
  ]
    .filter((value): value is string => value != null && Boolean(value.trim()))
    .join("\n\n");
  return (
    <Stack spacing={0.95}>
      <CodeSourceCard languageLabel={calculation.runtime === "sage" ? "Sage" : "Python"} source={calculation.code} />
      {output?.stdout.trim() ? (
        <Fragment>
          <Typography variant="subtitle2">Output</Typography>
          <InlineMarkdown content={`\`\`\`text\n${output.stdout.trim()}\n\`\`\``} mathSyntax={mathSyntax} sx={codeBlockStyles} />
        </Fragment>
      ) : null}
      {diagnostics ? (
        <Fragment>
          <Typography variant="subtitle2" color="error">Diagnostics</Typography>
          <InlineMarkdown content={`\`\`\`text\n${diagnostics}\n\`\`\``} mathSyntax={mathSyntax} sx={codeBlockStyles} />
        </Fragment>
      ) : null}
      {calculation.inputAttachmentIds.length > 0 ? (
        <Typography variant="body2" color="text.secondary">
          Inputs: {calculation.inputAttachmentIds.join(", ")}
        </Typography>
      ) : null}
      {artifacts.length > 0 ? (
        <GeneratedArtifactContent
          artifactRefs={artifacts.map((artifact) => ({
            artifact_name: artifact.name,
            caption: `Supporting calculation artifact: ${artifact.name}.`,
            alt_text: `Artifact generated by the ${calculation.runtime === "sage" ? "Sage" : "Python"} calculation: ${artifact.name}.`,
            python_code: calculation.code,
          }))}
          artifacts={artifacts}
          mathSyntax={mathSyntax}
        >
          <Typography variant="subtitle2">Generated artifacts</Typography>
        </GeneratedArtifactContent>
      ) : null}
      {artifacts.length === 0 && output && output.artifacts.length > 0 ? (
        <Stack spacing={0.5}>
          <Typography variant="subtitle2">Generated files</Typography>
          {output.artifacts.map((artifact) => (
            <Typography variant="body2" color="text.secondary" key={`${calculation.callId}:${artifact.name}`}>
              {artifact.name} · {artifact.mimeType} · {artifact.sizeBytes} bytes
            </Typography>
          ))}
        </Stack>
      ) : null}
    </Stack>
  );
});

const statusDisplay: Record<string, { label: string; color: string }> = {
  completed: { label: "Completed", color: "success" },
  partial: { label: "Partial", color: "warning" },
  failed: { label: "Failed", color: "error" },
};

export interface ComputeStructuredSectionProps {
  artifacts?: Artifact[] | null;
  artifactMessage?: unknown;
  mathSyntax?: string;
  status?: string;
  toolCalls: ComputeToolCall[];
}

export function ComputeStructuredSection({
  artifacts,
  artifactMessage,
  mathSyntax,
  status,
  toolCalls,
}: ComputeStructuredSectionProps) {
  const fallbackArtifacts = useMemo(
    () => (artifactMessage ? getArtifactsFromMessage(artifactMessage, "compute") : []),
    [artifactMessage],
  );
  const resolvedArtifacts = artifacts ?? fallbackArtifacts;
  const calculations = useMemo(() => collectCalculations(toolCalls), [toolCalls]);
  const runtimes = [...new Set(calculations.map((calculation) => calculation.runtime))];
  const statusInfo = typeof status === "string" ? statusDisplay[status] : undefined;
  const source = [...new Set(calculations.map((calculation) => calculation.code))].join("\n\n");
  const fileName = calculations.length === 1
    ? `calculation-${calculations[0].callId.slice(0, 8)}.py`
    : "calculations.py";
  if (calculations.length === 0) return null;
  return (
    <Stack spacing={0.5}>
      <Stack direction="row" spacing={0.75} useFlexGap={true} sx={{ flexWrap: "wrap", alignItems: "center", width: "100%" }}>
        {statusInfo ? <Chip size="small" color={statusInfo.color} label={statusInfo.label} /> : null}
        {runtimes.map((runtime) => (
          <Chip size="small" variant="outlined" label={runtime === "sage" ? "Sage" : "Python"} key={runtime} />
        ))}
        {calculations.map((calculation) =>
          calculation.output ? (
            <Chip
              size="small"
              variant="outlined"
              label={formatComputationDuration(calculation.output.durationMs)}
              key={`${calculation.callId}:duration`}
            />
          ) : null,
        )}
        {source ? (
          <Stack direction="row" sx={{ marginLeft: "auto", display: "flex", alignItems: "center", gap: 0.5, flexShrink: 0 }}>
            <DownloadSourceButton fileName={fileName} source={source} />
          </Stack>
        ) : null}
      </Stack>
      {calculations.map((calculation) => (
        <CalculationDetails
          calculation={calculation}
          artifacts={resolvedArtifacts.filter(
            (artifact) => artifact.originatingCallId === calculation.callId,
          )}
          mathSyntax={mathSyntax}
          key={calculation.callId}
        />
      ))}
    </Stack>
  );
}
